### ISSUE TITLE
Add support for hints

### ISSUE THREAD

**Issue by Milo123459** [rose-pine/alacritty#3]
With the new release of Alacritty, there are new features that need colouring.

@ThatOneCalculator - thank you

**Comment by Milo123459** [comment]
(More specifically the hints thing)

**Comment by Milo123459** [comment]
Where were these implemented? There weren't any new commits

**Comment by mvllow** [comment]
I don't personally use alacritty so a PR may be your best bet. This issue should remain open until fixed, though

**Comment by ThatOneCalculator** [comment]
Oh, I thought I added them lol, give me a sec

**Comment by ThatOneCalculator** [comment]
Done
